### ISSUE TITLE
file “cmapps_train_test_cross_domain.pt ” is missing,

### ISSUE THREAD

**Issue by 943fansi** [mohamedr002/CADA#3]
could you provide a copy of it?
I have some original txt files，like train_FD001.txt, test_FD001.txt, RUL_FD001.txt .How can I convert them into this "pt" file?

**Comment by shankangheng** [comment]
Have you solved this problem? I have the same problem

**Comment by 943fansi** [comment]
> Have you solved this problem? I have the same problem

Not yet. Do you know about transfer learning？

**Comment by shankangheng** [comment]
I'm doing it ! Contact me to discuss  qq：2577246902

**Comment by mohamedr002** [comment]
Hi all, sorry for the late response. You will find the data preprocessing file in the data folder. Then, I use my custom dataset class to load the data. the cross-domain train test is just a collection of different datasets together

**Comment by 943fansi** [comment]
> Hi all, sorry for the late response. You will find the data preprocessing file in the data folder. Then, I use my custom dataset class to load the data. the cross-domain train test is just a collection of different datasets together

Hi, mohamedr002. I understand what you mean, but I just can't find the code to save the dataset as a '.pt' file. Could you provide it so that I can run "main_cross_domains.py" successfully? Sincerely hope to get your help.

**Comment by shankangheng** [comment]
In other words, the missing Pt file is a combination of data from four different domains after data_processing?
Another question is whether the code does not contain statements calling the pre _training model. Do I need to carry out the pre training steps first? thank you

**Comment by mohamedr002** [comment]
@ Hi all, I have uploaded the data processing file that output the .pt dataset 
@943fansi @shankangheng 
'data/data_processing_train_test.py''

**Comment by 943fansi** [comment]
@mohamedr002 Thanks.
